<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post" id="form-validate-email" style="display:none">

       
        <p class="forgot"><?php echo $this->__('Please enter your email address below.') ?></p>
        <p class="forgot"><?php echo $this->__('You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
 
                <div class="input-box">
                    <input placeholder="Email Address" type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
       
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm2 = new VarienForm('form-validate-email', true);
//]]>
</script>
