     <script type="text/javascript">var PublicKeyMercadoPagoCustom = "APP_USR-6f9aa5b0-3ece-498d-84dd-5c4e7b8dc72f";</script>
     <script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>

<?php
$country = Mage::getStoreConfig('payment/mercadopago/country');
$coupon_mercadopago = Mage::getStoreConfig('payment/mercadopago_custom/coupon_mercadopago');
$_code = $this->getMethodCode();
$_quote = $this->helper('checkout/cart')->getQuote();
$grant_total = $_quote->getGrandTotal();
$_totals = $_quote->getTotals();
if (isset($_totals['mercadopago'])) {
    $grant_total = $grant_total - $_totals['mercadopago']->getValue();
}
$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true);
$logEnabled= Mage::getStoreConfigFlag('payment/mercadopago/logs');
$route = $this->getRequest()->getRequestedRouteName();
$customer = $this->getCustomerAndCards();
?>

<script>
    MercadoPagoCustom.enableLog(<?php echo $logEnabled?>);
    try {
        TinyJ('#mercadopago_checkout_custom');
        MercadoPagoCustom.getInstance().init();
    } catch (exception) {
        document.observe("dom:loaded", function() {
            MercadoPagoCustom.getInstance().init();
        });
    }
</script>

<style>
::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color:    #111;
}
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
   color:    #111;
   opacity:  1;
}
::-moz-placeholder { /* Mozilla Firefox 19+ */
   color:    #111;
   opacity:  1;
}
:-ms-input-placeholder { /* Internet Explorer 10-11 */
   color:    #111;
}
:placeholder-shown { /* Standard (https://drafts.csswg.org/selectors-4/#placeholder) */
  color:    #111;
}

.correctmargin{margin-bottom: 3%;}
</style>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/style.css'); ?>?nocache=<?php echo rand(); ?>"/>

<fieldset>
    <div id="mercadopago_checkout_custom">
        <ul class="form-list" id="payment_form_<?php echo $_code ?>" >


            <?php
            if ($coupon_mercadopago):
                $block = $this->getLayout()->createBlock('mercadopago/discount')->setCode($_code);
                echo $block->toHtml();
                ?>
                <script type="text/javascript">
                    try {
                        TinyJ('#mercadopago_checkout_custom');
                        MercadoPagoCustom.getInstance().initDiscount();
                    } catch (exception) {
                        document.observe("dom:loaded", function() {
                            MercadoPagoCustom.getInstance().initDiscount();
                        });
                    }
                </script>
                <?php
            endif;
            ?>

            <?php if ($customer !== false && isset($customer['cards']) && count($customer['cards']) > 0): ?>
                <li>
                    <ul id="mercadopago_checkout_custom_ocp">
                        <li id="cardId__mp">

                            <div><a id="use_other_card_mp" class="action_ocp"><?php echo $this->__('Use other card'); ?></a></div>

                            <label for="cardNumber"><?php echo $this->__('Payment Method'); ?></label>
                            <select id="cardId" name="payment[<?php echo $_code; ?>][cardId]" data-checkout="cardId" data-element-id="#cardId__mp">
                                <?php foreach ($customer['cards'] as $card) { ?>
                                    <option value="<?php echo $card["id"]; ?>" first_six_digits="<?php echo $card["first_six_digits"]; ?>" security_code_length="<?php echo $card["security_code"]["length"]; ?>">

                                        <?php echo $card["payment_method"]["name"].' '; ?><?php echo $this->__('ended in'); ?><?php echo ' '.$card["last_four_digits"]; ?>
                                    </option>
                                <?php } ?>
                            </select>

                            <input type="hidden" name="payment[<?php echo $_code; ?>][customer_id]" value="<?php echo $customer['id']; ?>">

                        </li>

                        <li id="securityCodeOCP__mp">
                            <label for="securityCode"><?php echo $this->__('CVV'); ?></label>
                            <input type="text" id="securityCodeOCP" class="required-entry" data-checkout="securityCode" maxlength="4" data-element-id="#securityCodeOCP__mp"/>

                            <p class="message-error error-E302 error-224 validation-advice"><?php echo $this->__('CVV is invalid.'); ?></p>
                        </li>
                    </ul>
                </li>

                <script>
                    try {
                        TinyJ('#use_other_card_mp');
                        MercadoPagoCustom.getInstance().initOCP();
                    } catch (exception) {
                        document.observe("dom:loaded", function() {
                            MercadoPagoCustom.getInstance().initOCP();
                        });
                    }
                </script>
            <?php endif; ?>

            <li>
                <ul id="mercadopago_checkout_custom_card">

                    <li style="display:none;" id="paymentMethod__mp">
                        <label for="paymentMethod"><?php echo $this->__('Payment Method'); ?></label>
                        <select id="paymentMethod" data-checkout="paymentMethod" name="payment[<?php echo $_code; ?>][paymentMethod]" data-element-id="#paymentMethod__mp" class="validate-select"></select>
                    </li>
    
                    <li id="cardNumber__mp">
                        <div><a id="return_list_card_mp" class="action_ocp"><?php echo $this->__('Return to cards list'); ?></a></div>

                        <input placeholder="Número de Tarjeta" type="text" id="cardNumber" data-checkout="cardNumber" data-element-id="#cardNumber__mp" class="fixwidth correctmargin stateselect input-text required-entry"/>            
                       

                        <p class="message-error error-payment-method-not-found error-E301 error-205 validation-advice"><?php echo $this->__('Card number is invalid.'); ?></p>

                        <p class="message-error error-payment-method-min-amount validation-advice"><?php echo $this->__('Cannot pay this amount with this payment_method_id.'); ?></p>

                    </li>

                    <li id="issuer__mp" >
                 
                        <select placeholder="Banco" id="issuer" name="payment[<?php echo $_code; ?>][issuer_id]" data-checkout="issuer" data-element-id="#issuer__mp">

                        </select>

                        <p class="message-error error-220 validation-advice"><?php echo $this->__('Select issuer'); ?></p>
                    </li>

                    <li id="expiration_date__mp">
                        <div id="box_month mes">
                            <select placeholder="Mes de vencimiento" id="cardExpirationMonth" data-checkout="cardExpirationMonth"  name="payment[<?php echo $_code; ?>][card_expiration_month]" data-element-id="#expiration_date__mp"  class="fixwidth correctmargin stateselect required-entry mp-validate-cc-exp">
                                <option>Mes de vencimiento</option>
                                <?php foreach ($this->getCcMonths() as $m => $v): ?>
                                    <option value="<?php echo $m ? $m : ''; ?>"><?php echo $v; ?></option>
                                <?php endforeach ?>
                            </select>

                            <p class="message-error error-325 error-208 validation-advice"><?php echo $this->__('El mes es inválido'); ?></p>
                        </div>

                        <div id="box_year">
                                     <select placeholder="Año de vencimiento" id="cardExpirationYear"  class="fixwidth  correctmargin stateselect required-entry validate-digits" data-checkout="cardExpirationYear" name="payment[<?php echo $_code; ?>][card_expiration_year]" data-element-id="#expiration_date__mp">
                                        <option>Año de vencimiento</option>
                                      <?php foreach ($this->getCcYears() as $y => $v): ?>
                                    <option value="<?php echo $y ? $y : ''; ?>"><?php echo $v; ?></option>
                                <?php endforeach ?>
                                </select>
                       
                              
                            </select>

                            <p class="message-error error-326 error-209 validation-advice"><?php echo $this->__('Year is invalid.'); ?></p>
                        </div>
                    </li>

                    <li id="cardholderName__mp">
               
                        <input placeholder="Nombre completo (como figura en la tarjeta)"  type="text" id="cardholderName" data-checkout="cardholderName" name="payment[<?php echo $_code; ?>][card_holder_name]" data-element-id="#cardholderName__mp" class="fixwidth  correctmargin stateselect required-entry" />

                        <p class="message-error error-316 validation-advice"><?php echo $this->__('El año es inválido.'); ?></p>
                    </li>

           

                    <li id="securityCode__mp">
                              <input placeholder="Código de seguridad"  class="fixwidth correctmargin stateselect input-text required-entry validate-digits" type="text" id="securityCode" data-checkout="securityCode" maxlength="4" data-element-id="#securityCode__mp"/>
                       

                        <p class="message-error error-E302 error-224 validation-advice"><?php echo $this->__('CVV is invalid.'); ?></p>
                    </li>

                    <li  style="display:none!important;" id="doc_type__mp">
                        <label style="display:none!important;" for="docType"><?php echo $this->__('Document Type'); ?></label>
                        <select style="display:none!important;" id="docType" data-checkout="docType" data-element-id="#doc_type__mp" name="payment[<?php echo $_code; ?>][doc_type]" class="fixwidth correctmargin stateselect input-text required-entry validate-digits"></select>

                        <p class="message-error error-322 error-212 validation-advice"><?php echo $this->__('Document Type is invalid.'); ?></p>
                    </li>

                    <li id="doc_number__mp">
                        <input placeholder="DNI" type="text" id="docNumber" class="fixwidth correctmargin stateselect input-text required-entry mp-validate-docnumber" data-checkout="docNumber" name="payment[<?php echo $_code; ?>][doc_number]" data-element-id="#doc_number__mp" class="fixwidth correctmargin stateselect input-text required-entry validate-digits"/>

                        <p class="message-error error-324 error-213 error-214 validation-advice"><?php echo $this->__('Document Number is invalid.'); ?></p>
                    </li>
                    <li id="installments__mp">
           
                <select placeholder="Cantidad de cuotas" id="installments" name="payment[<?php echo $_code; ?>][installments]" data-element-id="#installments__mp" class="fixwidth correctmargin stateselect validate-select"></select>

                <p class="message-error error-installment-not-work validation-advice"><?php echo $this->__('It was not possible to calculate the installments, click here and try again.'); ?></p>

                <p class="message-error error-011 validation-advice"><?php echo $this->__('An error has occurred. Please refresh the page.'); ?></p>

                <p class="message-error error-other validation-advice"><?php echo $this->__('Please validate your data.'); ?></p>

            </li>
                        
                </ul>
            </li>

            

            <li>
                <div id="mercadopago-loading">
                    <img src="<?php echo $this->getSkinUrl('mercadopago/images/loading.gif'); ?>" alt="loading"/>
                </div>
            </li>

            <li>

                <?php if ($this->getMethod()->getConfigData('banner_checkout') != ""): ?>
                    <img src="<?php echo $this->getMethod()->getConfigData('banner_checkout'); ?>" class="banner_checkout_mp"/>
                <?php endif; ?>

                <input type="hidden" class="total_amount" name="total_amount" value="<?php echo $grant_total; ?>"/>
                <input type="hidden" class="amount" name="amount" value="<?php echo $grant_total; ?>"/>
                <input type="hidden" class="mercadopago-discount-amount" name="mercadopago-discount-amount" value="0"/>
                <input type="hidden" class="site_id" name="site_id" value="<?php echo strtoupper($country); ?>"/>
                <input type="hidden" class="mercadopago-text-currency" value="<?php echo $this->__('$'); ?>">
                <input type="hidden" class="mercadopago-text-choice" value="<?php echo $this->__('Choice'); ?>">
                <input type="hidden" class="mercadopago-text-default-issuer" value="<?php echo $this->__('Default issuer'); ?>">
                <input type="hidden" class="mercadopago-text-installment" value="<?php echo $this->__('Enter the card number'); ?>">
                <input type="hidden" class="mercado_base_url" value="<?php echo $base_url; ?>">
                <input type="hidden" class="mercado_route" value="<?php echo $route; ?>">
                <input type="hidden" name="payment[<?php echo $_code; ?>][token]" type="text" value="" class="token"/>
                <input type="hidden" name="payment[<?php echo $_code; ?>][payment_method_id]" type="text" value="" class="payment_method_id"/>

                <input type="hidden" id="one_click_pay_mp" name="payment[<?php echo $_code; ?>][one_click_pay]" value="<?php echo count($customer['cards']) > 0 ? 1 : 0; ?>">
            </li>

       
        </ul>
    </div>
</fieldset>
