<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>

<style>
.form-list .field{
    width: 100% !important;
}
.input-box{
    margin-bottom: 0!important;
}
.form-list input.input-text, .form-list select{
    margin-bottom: 3% !important;
}
</style>
<div id="onestepcheckout-address-billing">
    <ul class="form-list">
        
        <li>
            <ul id="onestepcheckout-billing-address-list"<?php if ($this->customerHasAddresses()): ?> style="overflow: hidden;height: 0px;display:none"<?php endif; ?>>
            
                  <li class="fields">
                    <?php echo $this->getCustomerWidgetName()->toHtml(); ?>
                </li>
                <div class="input-box">
                            <input placeholder="Email" type="text" name="billing[email]" id="billing:email" title="<?php echo $this->__('Email') ?>" class="fixwidth correctmargin stateselect input-text validate-email validate-email-exist required-entry" value="<?php echo $this->getDataFromSession('email'); ?>" />
                        </div>
                <li class="fields">
                    <div class="field">
         
                        <div class="input-box">
                            <input placeholder="Teléfono" type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text validate-phone-br <?php echo $this->getAttributeValidationClass('telephone') ?> fixwidth correctmargin stateselect " id="billing:telephone" value="<?php echo $this->getDataFromSession('telephone'); ?>" placeholder="(xx) 4567-8900" />
                        </div>
                    </div>
                  
                </li>
               
                <li class="fields">
                    <div class="field">
              
                        <div class="input-box">
                            <input placeholder="Código postal" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="fixwidth correctmargin stateselect  input-text validate-number <?php echo $this->getAttributeValidationClass('postcode') ?>" value="<?php echo $this->getDataFromSession('postcode') ?>" maxlength="8" onblur="buscaCep('billing');" />
                        </div>
                    </div>
                
                </li>
                <?php $_streetValidationClass = $this->getAttributeValidationClass('street'); ?>
                <?php $streetValues = $this->getDataFromSession('street'); ?>
                <li class="wide">
                    <div class="input-box">
                        <input placeholder="Dirección" type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" class="input-text <?php echo $_streetValidationClass ?> fixwidth correctmargin stateselect" value="<?php echo (isset($streetValues[0])) ? $streetValues[0] : ''; ?>" autocomplete="off"/>
                    </div>
                </li>
             
                <li class="fields">
                    <div class="field">
            
                        <div class="input-box">
                            <input placeholder="Ciudad" type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="fixwidth correctmargin stateselect input-text <?php echo $this->getAttributeValidationClass('city') ?>" id="billing:city" value="<?php echo $this->getDataFromSession('city') ?>" />
                        </div>
                    </div>
                    <div class="field">
                   
                        <div class="input-box">
                            <select placeholder="Provincia" id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getDataFromSession('region_id') ?>");
                                //]]>
                            </script>
                            <input placeholder="Provincia" type="text" id="billing:region" name="billing[region]" value="<?php echo $this->getAttributeValidationClass('region') ?>"  title="<?php echo $this->__('State/Province') ?>" class="fixwidth correctmargin stateselect input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li style="display:none;" class="wide">
                    <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                    </div>
                </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                    <li class="control">
                        <label for="billing:save_in_address_book"><input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getDataFromSession('save_in_address_book')): ?> checked="checked"<?php endif; ?> class="checkbox" /><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else: ?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
            </ul>
        </li>    
        <?php if (!$this->isUseBillingAsShipping() && $this->canShip()): ?>
            <?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?><li class="osc-title"><?php echo $this->__('Shipping Address') ?></li><?php endif; ?>
            <li class="control">
                <label for="billing:use_for_shipping"> <input type="checkbox" name="billing[use_for_shipping]" value="1" title="<?php echo $this->__('Ship to same address') ?>" id="billing:use_for_shipping" <?php if ($this->isUseBillingAsShippingChecked()): ?> checked="checked"<?php endif; ?> class="checkbox" /><?php echo $this->__('Ship to same address') ?></label>
            </li>
        <?php else : ?>
            <li class="no-display"><input type="hidden" name="billing[use_for_shipping]" value="1" /></li>
        <?php endif; ?>
    </ul>
    <?php echo $this->getChildHtml('extra'); ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    <?php if (!$this->isCustomerLoggedIn()) : ?>
        $$("input[name*='radio_tipopessoa']").invoke('on', 'click', function() {
            var sel = $('billing:tipopessoa');
            setTipopessoaArea(this.value);
            for (var i = 0; i < sel.options.length; i++) {
                if (sel.options[i].text == this.value) {
                    sel.options[i].selected = true;
                }
            }

        });
        function setTipopessoaArea(arg){

            if (arg == 'Jurídica') {
                if ($('billing:taxvat')) {
                    $('billing:taxvat').maxLength = 18;
                    $('billing:ie').maxLength = 30;
                    $$('label[for="billing:ie"]').first().update('<em>*</em>IE (Inscrição Estadual)');
                    $$('label[for="billing:taxvat"]').first().update('<em>*</em>CNPJ');
                    $$('label[for="billing:firstname"]').first().update('<em>*</em>Razão social');
                    $$('label[for="billing:lastname"]').first().update('<em>*</em>N. Fantasia');
                    $('osc-billing-tipopessoa-area').hide();
                }
            } else {
                if ($('billing:taxvat')) {
                    $('billing:taxvat').maxLength = 14;
                    $('billing:ie').maxLength = 30;
                    $$('label[for="billing:taxvat"]').first().update('<em>*</em>CPF');
                    $$('label[for="billing:ie"]').first().update('<em>*</em>RG');
                    $$('label[for="billing:firstname"]').first().update('<em>*</em>Nome');
                    $$('label[for="billing:lastname"]').first().update('<em>*</em>Sobrenome');
                    $('osc-billing-tipopessoa-area').show();
                }
            }
        }
        <?php if (is_null($this->getDataFromSession('radio_tipopessoa'))): ?>
     
        <?php else: ?>
            if ($('billing:tipopessoa')) {
                setTipopessoaArea('<?php echo $this->getDataFromSession('radio_tipopessoa') ?>');
            }
        <?php endif; ?>
    Validation.add('validate-email-exist', '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>', function(value) {
        if (checkMail(value)) {
            var ok = false;
            var url = '<?php echo Mage::getBaseUrl(); ?>onestepcheckout/ajax/check_email/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'email=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                        if (obj.result !== 'clean') {
                            Validation.get('validate-email-exist').error = 'Email já cadastrado';
                                ok = false;
                        } else {
                                ok = true;
                        }
                    },
                    onComplete: function() {
                        if ($('advice-validate-email-exist-billing:email')) {
                          $('advice-validate-email-exist-billing:email').remove();
                        }
                    }
                });
            return ok;
        }else{
            Validation.get('validate-email').error = '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>';
        }
    });
    Validation.add('validate-taxvat', '<?php echo $this->__('This is a required field.') ?>', function(value) {
        if (validaCPF(value,0)) {
            var ok = false;
            var url = '<?php echo Mage::getBaseUrl(); ?>onestepcheckout/ajax/check_taxvat/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'taxvat=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                    if (obj.result !== 'clean') {
                        Validation.get('validate-taxvat').error = 'CPF/CNPJ já cadastrado';
                            ok = false;
                    } else {
                            ok = true;
                    }
                },
                onComplete: function() {
                    if ($('advice-validate-taxvat-billing:taxvat')) {
                        $('advice-validate-taxvat-billing:taxvat').remove();
                    }
                }
            });
            return ok;
         }else{
                 Validation.get('validate-taxvat').error = 'O CPF/CNPJ informado \xE9 inválido';
         }
    });
    <?php endif; ?>
    Validation.add('validate-zip-br', '<?php echo $this->__('Please enter a valid zip code. e.g. 12345678.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /(^\d{8}$)|(^\d{5}-\d{3}$)/.test(v);
    });
    Validation.add('validate-phone-br', '<?php echo $this->__('Please enter a valid phone number. for example, (xx) x4567-8900.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(\()?\d{2}(\))?(-|\s)?\d{5}(-|\s)\d{4}|(\()?\d{2}(\))?(-|\s)?\d{4}(-|\s)\d{4}$/.test(v);
    });
    
    if ($('billing:taxvat')) {
        $('billing:taxvat').addClassName('validate-taxvat');
        $('billing:taxvat').observe('keyup', function(event) {
            mascara(this, mdocumento);
        });
    }
    
    if ($('billing:telephone')) {
        $('billing:telephone').addClassName('validate-phone-br');
        $('billing:telephone').observe('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if ($('billing:fax')) {
        $('billing:fax').addClassName('validate-phone-br');
        $('billing:fax').observe('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if ($('billing:postcode')) {
        $('billing:postcode').addClassName('validate-zip-br');
        $('billing:postcode').observe('keyup', function(event) {
            this.maxLength = 8;
            mascara(this, sonumeros);
        });
    }
    if ($('billing:street1')) {
        $('billing:street1').observe('keyup', function(event) {
            this.maxLength = 40;
        });
    }
    if ($('billing:street2')) {
        $('billing:street2').observe('keyup', function(event) {
            this.maxLength = 5;
        });
    }
    if ($('billing:street3')) {
        $('billing:street3').observe('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if ($('billing:street4')) {
        $('billing:street4').observe('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if ($('billing:city')) {
        $('billing:city').observe('keyup', function(event) {
            this.maxLength = 30;
        });
    }
    if ($('billing:day')) {
        $('billing:day').observe('keyup', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:month').observe('keyup', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:year').observe('keyup', function(event) {
            this.maxLength = 4;
            mascara(this, sonumeros);

        });
    }
    //]]>
</script>
