<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="onestepcheckout_forgotbox" style="display: none;" class='op_login_area'>

<?php
$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$forgot_url	= str_replace('http:', 'https:', $forgot_url);  
?>
    <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form">
        <div class="boxcontent form_fields center">
            <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
			<div class='full'>
			
			
				<div class="data_area" id ="popup">
					<input placeholder="Email Address" type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email fixwidth" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" size="30" />
				</div>
            </div>
        </div>
        <div class="buttons-set center">
            <p class="back-link"><a href="javascript:void(0)" class="onestepcheckout_loginlink" onclick='open_login();'><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button btnmodallogin"><?php echo $this->__('Submit') ?></button>
            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/onestepcheckout/opc-ajax-loader_onestepcheckout.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('forgot-password-form', true);
    //]]>
    </script>
</div>
<?php }?>