
    <div class="contacto">
      <div class="section group">
        <div id="titulo" class="col span_8_of_8">
            <h1>Let´s get in touch </h1>
            <p>We'd love to hear about you, feel free to drop us a line or just call us! </p>
        </div>
      </div>  
    <div class="section group"> 
        
            <div class="col span_8_of_8">
               
                    <div id="phone">
                      <h1>801-501-8847 </h1>
                    </div>  

                  <form action="<?php echo Mage::getUrl(); ?>contacts/index/post/" id="contactForm" method="post">
                    <div class="fieldset cbp-mc-form">
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <label for="name" class="required"></label>
                                    <div class="input-box">
                                        <input placeholder="Name"  name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="email" class="required"></label>
                                    <div class="input-box">
                                        <input placeholder="E-mail" name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                                    </div>
                                </div>
                            </li>
                            <li class="wide">
                                <label for="comment" class="required"></label>
                                <div class="input-box">
                                    <textarea placeholder="comment" name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Send!') ?>" class="btncontact"><span><span><?php echo Mage::helper('contacts')->__('SUBMIT') ?></span></span></button>
                    </div>
                    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                  </form>


          
                      
                
                  

           
        
        
            </div>
    </div>
      
     </div>

<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>

