<style>

.mercadopago-title{
	font-family: montserrat !important;
	font-weight: 800 !important;
	font-size: 2em !important;
}
.mercadopago-subtitle{
	font-family: montserrat !important;
	font-weight: 400 !important;
	font-size: 1em !important;
	font-style: italic;
}
#box-mercadopago{
	text-align: center;
	margin-top: 5%;
}
#logo-mercadopago{
	text-align: center;
	width: 100% !important;
}
#logo-mercadopago img{
	float:none !important;
	width: 10% !important;
}

</style>

<div class="container">
<div id="box-mercadopago">


        <h2 class="mercadopago-title"><?php echo $this->__('Gracias por tu compra'); ?></h2>
         <h2 class="mercadopago-subtitle"><?php echo $this->__('Su orden está siendo procesada, a la brevedad recibirá un email para confirmar el envío o retiro de la misma'); ?></h2>
         
   
         
   

  
</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
</div>
</div>
