<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
?>




	<div class="container checkouttitle">
		<div class="row">
			<div class="col-md-12">
				<h2><?php echo $this->__('Checkout')?></h2>
			</div>
		</div>
	</div>		


	<div class="container checkoutlogin">
		<div class="row">
			<div class="col-md-12">

	<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
		<?php echo $this->getChildHtml('login');?>	
	<?php endif;?>

			</div>
		</div>
	</div>		



	<div class="clear"></div>





	<div class="container center">
		<div class="row">
			<div class="col-md-6">
				<div class="row">	
					<div class="col-md-12">	
						<div class="checkoutsubtitle1"></div>
					</div>	
				</div>	
				<div class="row">
					<div class="col-md-12">	
						<form id="opc-address-form-billing" method="post">
	        				<?php echo $this->getChildHtml('billing')?>
		        		</form>
		        	</div>		
				</div>
		        <div class="row">	
		        		<div class="col-md-12">	
						     <form id="opc-address-form-shipping" class="hidden" method="post">
			       				 <?php echo $this->getChildHtml('shipping')?>
			        		</form>
		        		</div>	
				</div>
			

			
		        	
		   
			</div>
				<div class="col-md-3">	
						
						<div class="checkoutsubtitle2"></div>
					
						<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
							 <div class="addresssub"><h3><?php echo $this->__('Payment details')?></h3></div>
						
							<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
						</div>
						
				
					

			</div>	
			<div class="col-md-3">	
			
					<div class="checkoutsubtitle3"></div>
					
					<div class="shipping-block">
			        	

						<p class="shippingh2">Shipping is</p>

						<p class="shippingh2"> on us!</p>

			        	
			        	<div id="shipping-block-methods">
							<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
						</div>
					</div>	

			
					
			</div>	
		





		</div>
	
    	
	
		
		<!-- <div class="discount-block">
			<h3><?php echo $this->__('Discount Codes')?></h3>
			<?php echo $this->getChildhtml('coupon');?>
		</div> -->

	

   
			<div class="row">
				<div class="col-md-12 ">	
				 		<div class="row">
							<div class="col-md-12 review">	
				        		<h3><?php echo $this->__('Review Your Order')?></h3>
				        	</div>
				        </div>		
				        <div id="opc-review-block">
						<?php echo $this->_getReviewHtml()?>
						</div>
				  
				</div>
			</div>

	</div>








<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>