
<?php $attributes = $this->getAllAttributes(); 
?>
<script type="text/javascript">
//<![CDATA[
var firstStepTemplate = '<div class="option-box" id="tag_{{id}}">'+
            '<table id="<?php echo $this->getFieldId() ?>_{{id}}" class="option-header" cellpadding="0" cellspacing="0">'+
            '<input type="hidden" id="<?php echo $this->getFieldId() ?>_{{id}}_is_delete" name="<?php echo $this->getFieldName() ?>[{{id}}][is_delete]" value="" />'+
			'<input type="hidden" id="<?php echo $this->getFieldId() ?>_{{id}}_previous_attributecode" name="<?php echo $this->getFieldName() ?>[{{id}}][previous_attributecode]" value="{{attribute_code}}" />'+
            '<input type="hidden" id="<?php echo $this->getFieldId() ?>_{{id}}_tag_id" name="<?php echo $this->getFieldName() ?>[{{id}}][tag_id]" value="{{tag_id}}" />'+
            '<thead>'+
                '<tr>'+
                    '<th class="tag-name" width="17%"><?php echo Mage::helper('magesitemap')->__('Name') ?> <span class="required">*</span></th>'+
                    '<th class="tag-type" width="17%"><?php echo Mage::helper('magesitemap')->__('Type') ?> <span class="required">*</span></th>'+
                    '<th class="tag-attcode" width="17%"><?php echo Mage::helper('magesitemap')->__('Attribute Code') ?></th>'+
                    '<th class="tag-sttvalue" width="17%"><?php echo Mage::helper('magesitemap')->__('Static Value') ?></th>'+
					'<th class="tag-sort_order" width="10%"><?php echo Mage::helper('magesitemap')->__('Sort Order') ?></th>'+
					'<th class="a-right"><?php echo $this->jsQuoteEscape($this->getDeleteTagButtonHtml()) ?></th>'+
				'</tr>'+
            '</thead>'+
            '<tr>'+
                '<td width="17%"><input type="text" class="required-entry input-text" id="<?php echo $this->getFieldId() ?>_{{id}}_name" name="<?php echo $this->getFieldName() ?>[{{id}}][name]" value="{{name}}"></td>'+
                '<td width="17%"><select id="<?php echo $this->getFieldId() ?>_{{id}}_type" name="<?php echo $this->getFieldName() ?>[{{id}}][type]" onchange="changeSelectType(this,{{id}})" class="{{required}}">'+
					'<option value=""><?php echo Mage::helper('magesitemap')->__('Select Type') ?></option>'+
					'<option value="1" ><?php echo Mage::helper('magesitemap')->__('Product Attribute') ?></option>'+
					'<option value="2" ><?php echo Mage::helper('magesitemap')->__('Product Link') ?></option>'+
					'<option value="3" ><?php echo Mage::helper('magesitemap')->__('Shipping Cost')?></option>'+
					'<option value="4" ><?php echo Mage::helper('magesitemap')->__('Tax')?></option>'+
					'<option value="5" ><?php echo Mage::helper('magesitemap')->__('Static Tag')?></option>'+
				'</select></td>'+
               // '<td><input type="text" id="{{id}}_attributecode" name="<?php echo $this->getFieldName() ?>[{{id}}][attribute_code]" value="{{attribute_code}}" class="required-entry"></td>'+
				'<td width="17%"><select id="{{id}}_selectattributecode" name="<?php echo $this->getFieldName() ?>[{{id}}][attribute_code]" >'+
					'<option value=""><?php echo Mage::helper('magesitemap')->__('Select Attribute Code')?></option>'+
					<?php
					foreach ($attributes as $attribute) {
					?>
					'<option value="<?php echo $attribute?>"><?php echo $attribute;?></option>'+
					<?php } ?>
				'</select></td>'+		
                '<td width="17%"><input class="input-text" type="text" id="{{id}}_staticvalue" name="<?php echo $this->getFieldName() ?>[{{id}}][static_value]" value="{{static_value}}"></td>'+
				'<td width="10%"><input class="validate-zero-or-greater input-text" type="text" id="<?php echo $this->getFieldId() ?>_{{id}}_sort_order" name="<?php echo $this->getFieldName() ?>[{{id}}][sort_order]" value="{{sort_order}}"></td>'+
				'<td>&nbsp;</td>'+
				
            '</tr></table></div>';
var tagOption = {
    div : $('product_options_container_top'),
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : firstStepTemplate,
    itemCount : 1,
	add : function(data) {
        this.template = new Template(this.templateText, this.templateSyntax);

        if(!data.id){
            data = {};
			data.id  = this.itemCount;
            data.type = '';
            data.tag_id = 0;
			data.required = 'required-entry';
        } else {
			data.required = '';
            this.itemCount = data.item_count;
        }
        Element.insert(this.div, {'after':this.template.evaluate(data)});
        this.itemCount++;
        this.bindRemoveButtons();
    },
	
	remove : function(event){
        var element = $(Event.findElement(event, 'div'));
		if(element){
            $('sitemap_'+element.readAttribute('id')+'_'+'is_delete').value = '1'; 
            element.addClassName('no-display');
            element.addClassName('ignore-validate'); 
            element.hide();
        }
    },
    bindRemoveButtons : function(){
        var buttons = $$('div.product-custom-options .delete-product-option');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.remove.bind(this));
            }
        }
    }
}

function setSelected(data)
{
	var typeoptions = $('<?php echo $this->getFieldId() ?>_'+data.tag_id+'_type').options;
	for(var i=0;i<typeoptions.length;i++)
	{
	if (data.type == typeoptions[i].getAttribute("value"))
		typeoptions[i].selected = true;
	}

	var attcodeoptions = $(data.tag_id+'_selectattributecode').options;	
	switch (data.type) {
	case '2':	
	case '3':	
	case '4':	
		$(data.tag_id+'_selectattributecode').hide();
		$(data.tag_id+'_staticvalue').hide();
		break;
	case '5':
		$(data.tag_id+'_selectattributecode').hide();
		$(data.tag_id+'_staticvalue').show();
		break;
	case '1':
		$(data.tag_id+'_selectattributecode').show();
		$(data.tag_id+'_staticvalue').hide();
		for (var i=0;i<attcodeoptions.length;i++)
		{
			if (data.attribute_code == attcodeoptions[i].getAttribute("value"))
			attcodeoptions[i].selected = true;
		}
		break;
	case '':
		$(data.tag_id+'_selectattributecode').show();
		$(data.tag_id+'_staticvalue').show();
		for (var i=0;i<attcodeoptions.length;i++)
		{
			if (data.attribute_code == attcodeoptions[i].getAttribute("value"))
			attcodeoptions[i].selected = true;
		}
		break;
	}	
}
	
if($('<?php echo $this->getAddButtonId() ?>')){
    Event.observe('<?php echo $this->getAddButtonId() ?>', 'click', tagOption.add.bind(tagOption));
}
<?php foreach ($this->getOptionValues() as $_value): ?>
    tagOption.add(<?php echo $_value->toJson() ?>);
	setSelected(<?php echo $_value->toJson() ?>);
<?php endforeach; ?>

//]]>
</script>
		

