<div class="entry-edit custom-options product-custom-options">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('magesitemap')->__('XML Tags') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
        <?php echo $this->getTagsBoxHtml() ?>
    </div>
</div>