<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<style>
.loginsub{
width: 100%;
border-bottom: 1px solid #ddd;
text-transform: uppercase;
    font-size: 1.5em;
    font-family: Lato,sans-serif;
    font-weight: 400;
    color: #373737;
    text-decoration: none !important;
    margin-top: 0 !important;
    padding: 2%;
    text-align: center;

}
.contenedor{
border: 1px solid #ddd;
    margin-top: 8%;
        margin-bottom: 8%;
    width: 30%;
    margin-left: 35%;
    max-width: 1170px;
}
.loginform{
text-align: center;
padding: 5%;

}
.botonlogin{

    font-family: Lato,sans-serif;
    background-color: transparent;
font-weight: 700;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #373737;
border-radius: 0;
color: #373737;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}

.botonlogin:hover{

    font-family: Lato,sans-serif;
font-weight: 700;
  background-color: transparent;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #3cd3ad;
border-radius: 0;
color: #3cd3ad;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}
.retrieve{
        font-family: Lato,sans-serif;
font-weight: 700;
  background-color: transparent;
font-size: 1em;
}
.fixwidth{
    width: inherit !important;
}
</style>
<div class="container" style="margin-top:5%;margin-bottom:10%;border: 1px solid #ddd;">

   <div  class="loginsub">Edit Account Information</div>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form class="loginform" action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <ul style="margin-top:2%" class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
              <div class="input-box">     
            <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>

          
        </ul>
    </div>

      <div class="fieldset" style="display:none;">
        <ul class="form-list">
            <li>
        
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" style="display:none;">
                    <input placeholder="Current Password" type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                
                    <div class="input-box">
                        <input placeholder="New Password" type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
             
                    <div class="input-box">
                        <input placeholder="Confirm Password"  type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
 <button class="botonlogin" type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
</form>



     
       
                 
       
            
  





   </div>

         

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
