<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<style>
.loginsub{
width: 100%;
border-bottom: 1px solid #ddd;
text-transform: uppercase;
    font-size: 1.5em;
    font-family: Lato,sans-serif;
    font-weight: 400;
    color: #373737;
    text-decoration: none !important;
    margin-top: 0 !important;
    padding: 2%;
    text-align: center;

}
.contenedor{
border: 1px solid #ddd;
    margin-top: 8%;
        margin-bottom: 8%;
    width: 30%;
    margin-left: 35%;
    max-width: 1170px;
}
.loginform{
text-align: center;
padding: 5%;

}
.botonlogin{

    font-family: Lato,sans-serif;
    background-color: transparent;
font-weight: 700;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #373737;
border-radius: 0;
color: #373737;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}

.botonlogin:hover{

    font-family: Lato,sans-serif;
font-weight: 700;
  background-color: transparent;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #3cd3ad;
border-radius: 0;
color: #3cd3ad;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}
.retrieve{
        font-family: Lato,sans-serif;
font-weight: 700;
  background-color: transparent;
font-size: 1em;
}
</style>
<div class="container" style="margin-top:5%;margin-bottom:10%;border: 1px solid #ddd;">

   <div  class="loginsub">Reset your password</div>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form class="loginform" action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top: 70px;">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                   
                    <div class="input-box">
                        <input placeholder="New Password" type="password" name="password" alt="password" id="password" class="input-text required-entry validate-password"  />
                    </div>
                </div>
                <div class="field">
                  
                    <div class="input-box">
                           <input placeholder="Confirm New Password" type="password" name="confirmation" alt="confirmation" id="confirmation"  class="input-text required-entry validate-cpassword"  />
                
                    </div>
                </div>
            </li>
        </ul>
    </div>


        <button class="botonlogin" type="submit" class="button" title="<?php echo $this->__('Reset a Password'); ?>"><span><span><?php echo $this->__('Submit'); ?></span></span></button>

</form>

                        
           


</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
   </div>

         


