
        <row>

            <div class=" row reviewtitles">

                    <div class="col-md-8"> 
                    <h3> <?php echo $this->__('Product Name') ?>  </h3>   
                    </div>
            

                     <div class="col-md-2"> 
                       <h3> <?php echo $this->__('Qty') ?> </h3> 
                    </div>
                     <div class="col-md-2"> 
                     <h3>   <?php echo $this->__('Subtotal') ?></h3> 
                    </div>





            </div>



        <?php foreach($this->getItems() as $_item): ?>
            <div class="row reviewseparate">
            <?php echo $this->getItemHtml($_item)?>
            </div>
        <?php endforeach ?>



        <?php echo $this->getChildHtml('totals'); ?>
  





<?php echo $this->getChildHtml('opc.newsletters');?>



<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">        
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>

    <script type="text/javascript">
    //<![CDATA[
    review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey(), '_secure' => $this->getRequest()->isSecure())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>


        </row>