<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<style>
.loginsub{
width: 100%;
border-bottom: 1px solid #ddd;
text-transform: uppercase;
    font-size: 1.5em;
    font-family: Lato,sans-serif;
    font-weight: 400;
    color: #373737;
    text-decoration: none !important;
    margin-top: 0 !important;
    padding: 2%;
    text-align: center;

}
.contenedor{
border: 1px solid #ddd;
    margin-top: 8%;
        margin-bottom: 8%;
    width: 30%;
    margin-left: 35%;
    max-width: 1170px;
}
.loginform{
text-align: center;
padding: 5%;

}
.botonlogin{

    font-family: Lato,sans-serif;
    background-color: transparent;
font-weight: 700;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #373737;
border-radius: 0;
color: #373737;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}

.botonlogin:hover{

    font-family: Lato,sans-serif;
font-weight: 700;
  background-color: transparent;
font-size: 1em;
text-transform: uppercase;
border: 3px solid #3cd3ad;
border-radius: 0;
color: #3cd3ad;
margin-top: 2%;
padding: 1% 4% 1% 4%;
-webkit-transition: all .3s;
-moz-transition: all .3s;
transition: all .3s;
}
</style>
<div class="container" style="margin-top:5%;margin-bottom:10%;border: 1px solid #ddd;">

   <div class="loginsub">Ingresá en tu cuenta</div>




   
    <form class="loginform" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        
<?php echo $this->getBlockHtml('formkey'); ?>
         
    

                    <ul class="form-list">
                        <li>
                          
                            <div class="input-box">
                                <input placeholder="Email" type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                         
                            <div class="input-box">
                                <input placeholder="Contraseña" type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <div class="section group">
                    <a style="text-transform:uppercase;font-size:0.9em;" href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Olvidaste tu contraseña?') ?></a>
                    </div>
                    <div class="section group">
                    <button class="botonlogin" type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Ingresar') ?></span></span></button>
                    </div>
    
     </div>


    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>

