<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>

    
	<div class="contenedorfoot">
		<div class="section group">
			
			<div id="social" class="col span_1_of_3">


				<a href="https://www.facebook.com/Ldbike">
					<span class="facebook">
		                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
							   width="36px" height="36px" viewBox="0 0 16 16" enable-background="new 0 0 16 16" xml:space="preserve">
							<path d="M8,0C3.582,0,0,3.582,0,8s3.582,8,8,8s8-3.582,8-8C16,3.581,12.418,0,8,0z M10.068,7.999L8.757,8l-0.001,4.8H6.957V8h-1.2
							  V6.346l1.2-0.001L6.955,5.371c0-1.35,0.366-2.171,1.955-2.171h1.324v1.655H9.406c-0.619,0-0.649,0.231-0.649,0.662L8.755,6.345
							  h1.488L10.068,7.999z"/>
						  </svg>
                 	 </span>
                </a>
            
                  <a href="http://instagram.com/lordbike">
                  	<span class="instagram">
		                  <svg version="1.1" id="Layer_3" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
						   width="36px" height="36px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
						   <g>
						  <ellipse fill-rule="evenodd" clip-rule="evenodd" cx="50.069" cy="49.844" rx="14.465" ry="14.017"/>
						  <path fill-rule="evenodd" clip-rule="evenodd" d="M72.458,50.626c0,11.981-10.024,21.693-22.389,21.693
						    c-12.365,0-22.389-9.712-22.389-21.693c0-2.147,0.324-4.221,0.924-6.18h-6.616v30.427c0,1.576,1.288,2.864,2.863,2.864H75.01
						    c1.576,0,2.865-1.288,2.865-2.864V44.446h-6.341C72.133,46.405,72.458,48.479,72.458,50.626z"/>
						  <path fill-rule="evenodd" clip-rule="evenodd" d="M66.457,36.235h8.141c1.784,0,3.242-1.458,3.242-3.242v-7.762
						    c0-1.785-1.458-3.243-3.242-3.243h-8.141c-1.785,0-3.243,1.458-3.243,3.243v7.762C63.213,34.776,64.672,36.235,66.457,36.235z"/>
						  <path fill-rule="evenodd" clip-rule="evenodd" d="M50,1.125C23.007,1.125,1.125,23.007,1.125,50S23.007,98.875,50,98.875
						    S98.875,76.993,98.875,50S76.993,1.125,50,1.125z M76.769,86.015H23.231c-5.087,0-9.246-3.764-9.246-9.244V23.23
						    c0-5.481,4.159-9.245,9.246-9.245h53.538c5.086,0,9.246,3.764,9.246,9.245v53.541C86.015,82.251,81.855,86.015,76.769,86.015z"/>
						   </g>
						  </svg>
                     </span>
                  </a>
				

				
			</div>
			
   			<div id="terms" class="col span_1_of_3">

   					<p class="terms"><a href="<?php  echo Mage::getBaseUrl(); ?>terminos">-Términos y condiciones-</a></p>

			</div>

			<div  id="terms" class="col span_1_of_3">
     			
	   		

     			<p class="terms"><a>-Lord bike 2015 Todos los derechos reservados-</a></p>
 
   			 </div>
 
   			 
		</div>
	</div>
		 		