<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>


    <?php if($this->getLastPageNum()>1): ?>
        <nav>
             <ul class="pagination">
        
        <?php if (!$this->isFirstPage()): ?>
          <li><a href="href="<?php echo $this->getPreviousPageUrl() ?>""><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>


        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

       

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="active"><a><?php echo $_page ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


    

        <?php if (!$this->isLastPage()): ?>
        <li><a href="<?php echo $this->getNextPageUrl() ?>"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        <?php endif;?>
        </ul>

    <?php endif; ?>

   

<?php endif ?>
