<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p class="text-login"><?php echo $this->__('Already registered?') ?> <a class="login-trigger signin-modal loginhere" data-modal="modal-login"><?php echo $this->__('LOGIN HERE')?></a></p>

<div class="md-modal md-effect-7" id="modal-login">
	<div class="md-content">
			<div class="md-modal-header">
				<button type="button" class="close">&times;</button>
			
			</div>	
			<div class="md-content-wrapper">
				<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		      		<?php echo $this->getBlockHtml('formkey'); ?>
			        <div>
						<ul class="form-list">
							<li>
				
								<div class="input-box">
									<input placeholder="Email address" type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
								</div>
							</li>
						<li>
		
							<div class="input-box">
								<input placeholder="Password" type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
							</div>
						</li>
						
						</ul>				
					</div>
					<input name="context" type="hidden" value="checkout" />
				</form>
				
				<?php echo $this->getChildhtml('forgotPassword');?>
			</div>
			<div class="md-modal-footer">

				<div  id="login-button-set">
					<div class="row">
					<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left restore-account"><?php echo $this->__('Forgot Your Password?') ?></a>	
					</div>
					<div class="row">
					<button type="button" class="btn btnlogin"><span><span><?php echo $this->__('Login') ?></span></span></button>
					</div>
				</div>	

				<div   id="forgotpassword-button-set" style="display:none">	
					<div class="row">	        	
		        	<p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>

		        	</div>	
		        	<div class="row">

		        	<button type="button" title="<?php echo $this->__('Submit') ?>" class="btn btnlogin"><span><span><?php echo $this->__('Submit') ?></span></span></button>
		        	</div>
    			</div>


			</div>
	</div>
</div>
<div class="md-overlay"></div>	
	
	
<script type="text/javascript">
    //<![CDATA[
        var dataForm1 = new VarienForm('login-form', true);
    //]]>
</script>
<div class="clear move-columns"></div>


