<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>

<style>
.chktitle{
    font-family: montserrat;
    font-size: 1.5em;
    font-style: italic;
    font-weight: bold;
    margin-top: 10%;
}
.opc .step{
    padding: 0 !important;
}
.contenedorfoot{
    display:none !important;
}
</style>
<div class="row" style="text-align:center;">
    <form style="margin-top:2.5%;" id="onestepcheckout-general-form" method="post" action="#">

        <div class="col-md-6">
            <h2 class="chktitle">Información de envio</h2>
            <div class="opc">
                <div class="section allow active">
                    <?php echo $this->getChildHtml('address'); ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="opc">
                <div class="section allow active">
                    <h2 class="chktitle">Información de pago</h2>
                     <div id="onestepcheckout-payment-method-wrapper">
                        <?php echo $this->getChildHtml('paymentmethod'); ?>
                    </div>
                 
                   
                </div>
            </div>
        </div>
        <div class="col-md-12">

            <!--
                 <h2 class="chktitle">Forma de envio</h2>
               <div id="onestepcheckout-shipping-method-wrapper">
                        <?php echo $this->getChildHtml('shippingmethod'); ?>
                    </div>

                  -->  
            <div class="opc">
                <div class="section allow active">
                    <?php $blockNumberClass = (!is_null($this->getBlockNumber(false))) ? "onestepcheckout-number-4" : ""; ?>
               
                  
                </div>
                <div class="section allow">
                    
                    <div id="onestepcheckout-place-order">
                        <button type="button" class="btncart  button btn-proceed-checkout btn-checkout" title="<?php echo $this->__('Place Order Now'); ?>" id="onestepcheckout-place-order-button">
                            <span><span class="onestepcheckout-place-order-title"><?php echo $this->__('Realizar Compra'); ?></span></span>
                            <span class="onestepcheckout-place-order-amount hide hidden" ><?php echo $this->getGrandTotal(); ?></span>
                        </button>
                        <div class="onestepcheckout-place-order-please-wait">
                            <img src="<?php echo $this->getSkinUrl('onestepcheckout/images/ajax-loader.gif') ?>" />
                            <?php echo $this->__('Please wait, processing your order...') ?></div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div id="onestepcheckout-popup" class="onestepcheckout-popup" style="display:none">
        <div id="onestepcheckout-popup-content" class="onestepcheckout-popup-content"></div>
        <div id="onestepcheckout-popup-accept" class="onestepcheckout-popup-accept">
            <button type="button"><?php echo $this->__('ACCEPT'); ?></button>
            <a href="javascript:void(0)"><?php echo $this->__('Close'); ?></a>
        </div>
    </div>
    <div id="onestepcheckout-overlay" class="onestepcheckout-popup-overlay" style="display:none"></div>
    <script type="text/javascript">
        var OSCForm = new OnestepcheckoutForm({
            formId: 'onestepcheckout-general-form',
            cartContainerSelector: "#onestepcheckout-order-review-cart-wrapper",
            // validate shipping and payment
            shippingMethodName: 'shipping_method',
            shippingMethodAdvice: '#onestepcheckout-shipping-method .validation-advice',
            shippingValidationMessage: '<?php echo $this->__('Please specify shipping method.'); ?>',
            shippingMethodWrapperSelector: '#onestepcheckout-shipping-method .sp-methods',
            paymentMethodName: 'payment[method]',
            paymentMethodAdvice: '#onestepcheckout-payment-method dl+.validation-advice',
            paymentValidationMessage: '<?php echo $this->__('Please specify payment method.'); ?>',
            paymentMethodWrapperSelector: '#onestepcheckout-payment-method .sp-methods',
            //place order functionality
            placeOrderUrl: '<?php echo $this->getPlaceOrderUrl(); ?>',
            successUrl: '<?php echo $this->getUrl('checkout/onepage/success'); ?>',
            granTotalAmountSelector: '.onestepcheckout-place-order-amount',
            placeOrderButtonSelector: 'onestepcheckout-place-order-button',
            pleaseWaitNoticeSelector: '.onestepcheckout-place-order-please-wait',
            overlayId: 'onestepcheckout-place-order-overlay',
            disabledClassName: 'onestepcheckout-place-order-button-disabled',
            popup: {
                overlaySelector: "#onestepcheckout-overlay",
                containerSelector: "#onestepcheckout-popup",
                contentContainerSelector: "#onestepcheckout-popup-content",
                acceptContainerSelector: "#onestepcheckout-popup-accept",
                buttons: {
                    accept:{
                        selector: "#onestepcheckout-popup-accept button",
                        enabled: false
                    },
                    close:{
                        selector: "#onestepcheckout-popup-accept a",
                        enabled: false
                    }
                }
            }
        });
    </script>
</div>

