<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>


<html>

<head>
<?php echo $this->getChildHtml('head') ?>
<script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css' rel='stylesheet' />

</head>
<style>
body{
padding-top: 0px !important;

}
</style>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

<!--    <?php echo $this->getChildHtml('after_body_start') ?> -->
      
 
  <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('header') ?>
    



    <div class="contacto container ">
    <div class="section group">
        <a  class"contactlink">
        <div class="contacttexto contactgrid1 col span_4_of_8">
            <h2>Teléfono/<span>011-4781-4984</span></h2>
          


        </div> 
         </a>
          <a  class"contactlink">
        <div class="contacttexto contactgrid2 col span_4_of_8">
             <h2>E-mail/<span>info@lordbike.com.ar</span></h2>
         



        </div>
          </a> 
    </div>
    <div class="section group">
        <div class="contactgrid3 col span_8_of_8">
                    
      <div id="map"></div>

        </div> 
    </div>    
    </div>


    <?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>


</body>

<script>

L.mapbox.accessToken = 'pk.eyJ1IjoidGF2aWFsbWFkYSIsImEiOiJTcE1hSjdjIn0.5pvHq55siHqbWpYT5b8Qeg';
var map = L.mapbox.map('map', 'tavialmada.lbom2o30') .setView([-34.57947,-58.45398], 15);


var marker = L.mapbox.featureLayer({
    type: 'Feature',
    geometry: {
        type: 'Point',
        coordinates: [-58.45398,-34.57947]
    },
    properties: {
        title: '- Av.Álvarez Thomas 853 -',
        description: 'Lunes-Viernes: 12:00-20:00 Sábados: 10:30-15:00',
        'marker-color': '#111111'
    }
}).addTo(map);


// Iterate over the featureLayer we've called "marker"
// and open its popup instead of clicking to trigger it.
marker.eachLayer(function(m) {
  
  m.openPopup();
});


</script>

</html>
