<?php
/**
* The MIT License (MIT)
*
* Copyright (c) 2011-2014 Webcomm Pty Ltd
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
?>
<?php
/**
* Template for Mage_Page_Block_Html
*/
?>
<!DOCTYPE html>


<html>
  
  <head><meta http-equiv="Content-Type" content="text/html; charset=gb18030">
  <?php echo $this->
getChildHtml('head') ?>

<style type="text/css">
.portada{
    z-index:10;
      position:absolute ;
    top: 0;
    max-height: 400px;
    width: 100%;
    height: auto;

}
h2 { 
   position:absolute;
  
     z-index: 11;
    font-family: Montserrat;
    font-weight: 400;
    font-style: italic;
    font-size: 3em!important;
    color:#1dd2af;
    text-transform: uppercase;
    left: 0;
    padding-left: 5%;
    padding-top: 5%;
    float:left;
}
h3 { 

     z-index: 11;
    font-family: Montserrat;
    font-weight: 400;
    font-size: 1.2em!important;
    color:#222;
    text-transform: uppercase;
    padding:1.2%;
}
.fixoverview{
  height:auto;
  position: relative;
  margin-top: 2.5%;
   display: table;
  width: 100%;
}
.fixoverviewtext{

      font-family: Utopia, Georgia;
    font-weight: normal;
    font-size: 1.7em;
    color: #444444;
    line-height: 1.5;
}

.vcenter {
    display: inline-block;
    vertical-align: middle;
    float: none;
}
.logomonk{
  position: absolute;
  width: 10%; 
  z-index: 50;
      top: 10%;
    right: 5%;
}
</style>


  </head>
  <body>

    
 
  <?php echo $this->getChildHtml('content') ?>
  
    <?php echo $this->
getChildHtml('header') ?>
  
    <img class="portada img-responsive" src="<?php echo $this->getSkinUrl('images/bw2.jpg'); ?>"  alt="">

          

    </div>
    <div style="margin-top:18%;" class="container">
        <div class=" fixoverview section group">
             <div   class=" mobilehide vcenter col span_2_of_8">
              <span style="margin-right:5%;float:right;font-size:1.5em;"class=" centeralign glyphicon glyphicon-minus" aria-hidden="true"></span>
            </div>
            <div  style="text-align:center;margin-left:0 !important;" class=" vcenter col span_4_of_8">
              <p class="centeralign fixoverviewtext">¿Estás buscando una bicicleta personalizada?</p><p class="fixoverviewtext"> Escribinos a  <a href="http://lordbike.com.ar/contacto"style="text-transform:uppercase; font-weight:700; color:#3333;font-family:Montserrat; font-size:0.8em;">info@lordbike.com.ar</a><p class="fixoverviewtext">para obtener más información!</p>




            </div>
            <div  style="margin-left:0 !important;"class="mobilehide  vcenter  col span_2_of_8">
             <span style="margin-left:5%;float:left;font-size:1.5em;"class="centeralign glyphicon glyphicon-minus" aria-hidden="true"></span>
            </div>


        </div>  

      </div>
    



      <div style="text-align:center;width:100%;height:auto;background-color:#bdc3c7;margin-top:2.5%;margin-bottom:0 !Important;">
        <h3 style="margin-bottom:0 !Important;">Proyectos realizados</h3>

      </div>  

            <div class="catalog ">

       



        
                     <div class="section group">

              
                <?php     
                    $category_id=49;
                    $products = Mage::getModel('catalog/category')->load($category_id);
                    $productslist = $products->getProductCollection()->addAttributeToSelect('*')->setOrder('price', 'ASC');;

                  ?>        
              
                   <?php foreach ($productslist   as $product){?>
                 
                                                
                                                  <div style="padding:0 !important;" id="ver" class="item col-md-4">
                                                       <img src=" <?php echo $this->helper('catalog/image')->init($product, 'small_image'); ?>" />
                                                  
                                                  </div>
                                              
                                
                
                    <?php
                    }
                    ?>
                   
                </div> 
              
  </div>









 
  <?php echo $this->getChildHtml('footer') ?>

 


 

<script>

 (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.src = 'http://assets.gfycat.com/js/gfyajax-0.517d.js';
    s.parentNode.insertBefore(g, s);

}(document, 'script'));
</script>

  </body>

</html>
