<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html>









<head>

<?php echo $this->getChildHtml('head') ?>

<style>

.item p {
    font-family: Montserrat;
    font-style: italic;
    font-weight: 400;
    font-size: 4em;
    color: #ecf0f1;
    text-transform: uppercase;
}
.disena:hover  .disenatext{
  color:#1abc9c;
        -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all  0.3s  ease-in-out;
  -o-transition: all  0.3s  ease-in-out;
  transition: all  0.3s  ease-in-out;
}
.homevideo{
background-color: black !important;
}
.hometop {
  background-color: black !important;
}
.bird{
  width: 60%;
  height: auto;
}

.rojitext{
  font-size: 2em;
  font-family: montserrat;
  font-weight: 800;
  color: white;
  font-style: italic;
  margin-top: -5%;
}
.newlinetext{
  font-size: 1em;
  font-family: montserrat;
  font-weight: 800;
  color: white;
  text-transform: uppercase;
  margin-top: 10%;
}
.vermodelos{
    position: relative;
    width: 50%;
    z-index: 10 !important;
    border: 3px solid #ffffff;
    height: auto;
    background-color: transparent;
    cursor: pointer;
    padding: 2%;
     margin-top: 5%;
    -webkit-transition: color 0.2s ease, border 0.2s ease;                  
    -moz-transition: color 0.2s ease, border 0.2s ease;              
    -o-transition: color 0.2s ease, border 0.2s ease;  
    -ms-transition:color 0.2s ease, border 0.2s ease;   
    transition:color 0.2s ease, border 0.2s ease;  



}


.vermodelos h3{
  font-family: montserrat;
  font-size: 1em;
  text-transform: uppercase;
  font-weight: 800;
  font-style: italic;
    color: #ffffff;
    -webkit-transition: all 0.2s ease;                  
    -moz-transition: all 0.2s ease;                 
    -o-transition: all 0.2s ease;   
    -ms-transition: all 0.2s ease;          
    transition: all 0.2s ease;
    margin-bottom: 0!important;
}
.vermodelos span{
  color:#ffffff !important;
  -webkit-transition: all 0.2s ease;                  
    -moz-transition: all 0.2s ease;                 
    -o-transition: all 0.2s ease;   
    -ms-transition: all 0.2s ease;          
    transition: all 0.2s ease;
}
.vermodelos:hover h3{
 color: rgba(52, 152, 219,1) !important;


}
.vermodelos:hover span{
 color: rgba(52, 152, 219,1) !important;


}
.vermodelos:hover{

 border: 3px solid  rgba(52, 152, 219,1) !important;


}
.bannerroji{
  height:87%;
  width: 87%;
  border:5px solid #ffffff;
  margin-left: 6.5%;
  padding: 10%;
  text-align: center;
}
.rojicontainer{

  -webkit-flex-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: center;
  text-align: center;
  background-color: black !important;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;


}
.videocontainer{
  -webkit-flex-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: center;
  text-align: center;
  background-color: black !important;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  flex:1;
}
.videocontainer .overlay{
  cursor:initial !important;
  z-index: 1;
}


@media (min-width: 769px){
.rojirow{
  -webkit-flex-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: center;
  text-align: center;
  background-color: black !important;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;

}
}
@media (max-width: 768px){
.bannerroji{
  margin-bottom: 5% !important;
}
}

</style>




</head>
<body style="background-color:#fff !important;">
 <?php echo $this->getChildHtml('header') ?>
      

<?php echo $this->getChildHtml('content') ?>

     
      
      <div style="  background-color: black !important;" class="rojirow row">
      
            <div  class="col-md-8" >
                <div style="cursor:none!important;" class="videocontainer" ><!-- class of active since it's the first item -->
                  <img style="cursor:none!important;" class="gfyitem" data-id="FatalScornfulBubblefish" data-controls="false" data-dot="false" data-perimeter="false" />
                </div>
            </div>
            <div  class="col-md-4 rojicontainer" >
                <div class="bannerroji">
                    <div class="col-md-12">
                      <img class="bird" src="<?php echo $this->getSkinUrl('images/bird.png'); ?>" ></img>
                    </div>
                    <h2 class="rojitext">Roji</h2>
                    <h2 class="newlinetext">Nueva línea de bicicletas!</h2>
                    <a href="<?php  echo Mage::getBaseUrl(); ?>plegables">
                       <button class="vermodelos" >
                          <div class="vcenter" style="position:relative;">
                          <h3 style="margin-top:0 !important;">Ver Modelos  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></h3> 
                        </div>
                      </button>
                   </a>
               </div>   

            </div>

       
      </div>


   

 <div class="section group">

        <div style="text-align:center;background:#F5F5F5; position: relative;" class="destacadosgrid col span_2_of_8">
    
          <a  class="destacadoslink" href="http://lordbike.com.ar/bicicletas"> 

           <h2   id="hover-content" style="

             
                position: absolute;
                  top: 42%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                font-family: Lato,sans-serif;
                 font-weight: bold;
                  font-size:2em; 
                  text-transform:uppercase;
                  color:#111;
                  font-style:italic;

              ">PLEGABLES</h2>
        <img style="display:initial !important;"class="img-responsive" src="<?php echo $this->getSkinUrl('images/destacados/n8.png'); ?>"  alt="">
        <div class="overlay"> </div>
         </a>

      </div>  
      


      <div style="text-align:center;background:#EEEEEE;" class="destacadosgrid col span_2_of_8">
    <a class="destacadoslink" href="http://lordbike.com.ar/cascos"> 
        <h2   id="hover-content" style="

                  position: absolute;
                  top: 42%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                font-family: Lato,sans-serif;
                 font-weight: bold;
                  font-size:2em; 
                  text-transform:uppercase;
                  color:#111;
                  font-style:italic;

              ">CASCOS</h2>
         <img style="display:initial !important;" class="img-responsive" src="<?php echo $this->getSkinUrl('images/destacados/morrison.png'); ?>"  alt=""> 
        <div class="overlay"> </div>
         </a>


      </div>   
      <div  style="text-align:center;background:#E0E0E0;" class="destacadosgrid col span_2_of_8">
            
         
                  <a class="destacadoslink" href="http://lordbike.com.ar/equipaje"> 
                      <h2   id="hover-content" style="

                  position: absolute;
                  top: 42%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                font-family: Lato,sans-serif;
                 font-weight: bold;
                  font-size:2em; 
                  text-transform:uppercase;
                  color:#111;
                  font-style:italic;

              ">EQUIPAJE</h2>
        <img style="display:initial !important;" class="img-responsive" src="<?php echo $this->getSkinUrl('images/destacados/marruecos.png'); ?>"  alt="">
         <div class="overlay"> </div>
          </a>



      </div>    
            <div style="text-align:center;background:#BDBDBD; position: relative;" class="destacadosgrid col span_2_of_8">
    
          <a  class="destacadoslink" href="http://lordbike.com.ar/otros"> 

           <h2   id="hover-content" style="

                  position: absolute;
                  top: 42%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                font-family: Lato,sans-serif;
                 font-weight: bold;
                  font-size:2em; 
                  text-transform:uppercase;
                  color:#111;
                    font-style:italic;

              ">OTROS</h2>
        <img style="display:initial !important;" class="img-responsive" src="<?php echo $this->getSkinUrl('images/destacados/perch.png'); ?>"  alt="">
        <div class="overlay"> </div>
         </a>

      </div>  
  


         

    </div>  


    <div style="border-top:2px solid #222;" class="social">
      <div style="text-align:center; background-color: rgba(189, 195, 199,0.8) !important;height:auto;" class="socialspan col span_5_of_8">

        <h2   style="margin-bottom: 20px!important;color:#222;font-family: Lato,sans-serif; font-weight: bold; font-size:1em; text-transform:uppercase;" >BLOG</h2>
  
  <?php 
$content = '';
$url = "https://blog.lordbike.com.ar/magentocontent-3/";
$ch = curl_init();
curl_setopt ($ch, CURLOPT_URL, $url);
curl_setopt ($ch, CURLOPT_HEADER, 0);
ob_start();
curl_exec ($ch);
curl_close ($ch);
$content = ob_get_contents();
ob_end_clean();
echo $content; 
?>








      </div> 

       <div style="text-align:center;    background-color: #ffffff !important;height:auto !important;" class="socialspan col span_3_of_8">

      <h2   style="  font-family: Lato,sans-serif; font-weight: bold; font-size:1em; text-transform:uppercase;" >instagram</h2>

        <div id="instafeed"  style="text-align:center; margin-top:10%";></div> 

      </div> 
     </div> 



   
    <?php echo $this->getChildHtml('footer') ?>
  </div>

  

<?php echo $this->getChildHtml('before_body_end') ?>




<script>

 jQuery( document ).ready(function( $ ) {

    $('#carousel').carousel({
      interval: 3000
    });
     $('#carousel2').carousel({
      interval: 3000
    });
});





 </script> 

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/instafeed.min.js'); ?>"></script>
<script type="text/javascript">

if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
    var userFeed = new Instafeed({
        get: 'user',
        userId: 520962122,
        limit:4,
        resolution: 'thumbnail',
        accessToken: '520962122.0de90bd.1d3e462d800a467da77f9b5ad26dffc9',
        template: '<a style="padding:2%;"class="instahover"href="{{link}}"><img  class="" src="{{image}}" /></a>'

    });
    userFeed.run();
} 
 else{
     var userFeed = new Instafeed({
        get: 'user',
        userId: 520962122,
        limit:6,
        resolution: 'low_resolution',
        accessToken: '520962122.0de90bd.1d3e462d800a467da77f9b5ad26dffc9',
        template: '<a style="padding:2%;"class="instahover"href="{{link}}"><img  class="" src="{{image}}" /></a>'

    });
    userFeed.run();
 
 
 
}



</script>

<style>
  .media-flex {
    position: relative;
    height: 0px;
  }
  .media-flex .gfyitem > div,
  .media-flex .gfyitem .gfyPreLoadCanvas,
  .media-flex .gfyitem .gfyVid,
  .media-flex .gfyitem  .gfyGif {
    position: absolute !important;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 100% !important;
    height: 100% !important;
  }
  .gfyDotCanvas{
    display:none!important;
  }
  .gfyPreLoadCanvas{
    display: none;
  }
</style>

<script type="text/javascript" src="https://assets.gfycat.com/gfycat.js">
</script>


</body>
</html>
