<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>


<html>


<head>
<?php echo $this->getChildHtml('head') ?>

</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('header') ?>




    <div class="shippings">
        
       <h1> Privacy Policy</h1>

<p>Your trust and confidence are our highest priority. Please read how this 

website collects and uses the information that you provide to us.</p>

<p>This website is operated by “Urban Bikes LLC”.

Throughout the site, the terms “we”, “us” and “our” refer to “

Urban bikes LLC”. “Urban Bikes LLC” offers this website and services

under the brand name “Foldway”, including all information, tools and 

services available from this site to you, the user, conditioned upon your 

acceptance of all terms, conditions, policies and notices stated here.

</p><p>By visiting our site and/ or purchasing something from us, you engage 

in our “Service” and agree to be bound by the following terms and 

conditions (“Terms of Service”, “Terms”), including those additional 

terms and conditions and policies referenced herein and/or available by 

hyperlink. These Terms of Service apply to all users of the site, including 

without limitation users who are browsers, vendors, customers, 

merchants, and/ or contributors of content.

</p><p>Please read these Terms of Service carefully before accessing or using 

our website. By accessing or using any part of the site, you agree to be 

bound by these Terms of Service. If you do not agree to all the terms 

and conditions of this agreement, then you may not access the website 

or use any services. If these Terms of Service are considered an offer, 

acceptance is expressly limited to these Terms of Service.

</p><p>Any new features or tools which are added to the current store shall 

also be subject to the Terms of Service. You can review the most current 

version of the Terms of Service at any time on this page. We reserve the 

right to update, change or replace any part of these Terms of Service by 

posting updates and/or changes to our website. It is your responsibility 

to check this page periodically for changes. Your continued use of or 

access to the website following the posting of any changes constitutes 

acceptance of those changes.

<h2>What we do with your information?</h2>

</p><p>When you register or purchase something from our store, as part of 

the buying and selling process, we collect the personal information you 

give us such as your name, address and email address, billing address or 

credit card information.

</p><p>We use this information for the following general purposes: products 

and services provisioning, billing, identification and authentication, 

services improvement, contact, marketing activities and research.

When you browse our store, we also automatically receive your 

computer’s internet protocol (IP) address in order to provide us with 

information that helps us learn about your browser and operating 

system.

<h2>Email marketing (if applicable)</h2>

</p><p> With your permission, we may send you 

emails about our store, new products and other updates.

</p><p>When you provide us with personal information to complete a 

transaction, verify your credit card, place an order, arrange for a delivery 

or return a purchase, we imply that you consent to our collecting it 

and using it for that specific reason and you agree with the fact that 

sometimes we also might use and ask your personal information for 

marketing reasons.

</p>




<p>We collect information we need to allow you place and confirm your 

order. We do not sell or give away user information except in cases 

where you specifically request it. Your participation in any promotion is 

strictly optional.

</p><p>You must not transmit any worms or viruses or any code of a destructive 

nature and respect our intellectual property.

<h2>Privacy of user information </h2>

</p><p>We collect the information volunteered by the consumer on the site 

registration process or other procedures such as survey information and 

we aggregate information on what pages consumers’ access or visit 

and other. The information we collect is used to improve the quality 

of our service, and is not shared with or sold to other organizations for 

commercial purposes, except to provide you with products or services, 

when we have your permission, or under the circumstances described 

below.</p>

<p>• We may collect the following information:</p>

<p>• Name</p>

<p>• Contact information including email address</p>

<p>• Demographic information such as postcode, preferences and interests</p>

<p>• Other information relevant to customer surveys and/or offers</p>



<p>• It is necessary to share information in order to investigate, 

prevent, or take action regarding illegal activities, suspected fraud, 

situations involving potential threats to the physical safety of any 

person, violations of Terms of Service, or as otherwise required by law.

<p>• We may transfer information about you if Urban bikes LLC is 

acquired by or merged with another company. In this event, Urban 

bikes LLC will provide notice before information about our customers is 

transferred and becomes subject to a different privacy policy.</p>

<p>•We sometimes use other companies (third-party service 

providers) to perform functions on our behalf. Examples include fulfilling 

orders, delivering packages or payment processing. They need access to 

some personal information in order to perform their duties but may not 

use this information for other purposes.</p>

<p>In general, the third-party providers used by us will only collect, use 

and disclose your information to the extent necessary to allow them to 

perform the services they provide to us.</p>

<p>However, certain third-party service providers, such as payment 

gateways and other payment transaction processors, have their own 

privacy policies in respect to the information we are required to provide 

to them for your purchase-related transactions.</p>

<p>For these providers, we recommend that you read their privacy policies 

so you can understand the manner in which your personal information 

will be handled by these providers.</p>

<p>In particular, remember that certain providers may be located in or have 

facilities that are located in a different jurisdiction than either you or us. 

So if you elect to proceed with a transaction that involves the services 

of a third-party service provider, then your information may become 

subject to the laws of the jurisdiction(s) in which that service provider or 

its facilities are located.</p>

<p>Once you leave our store’s website or are redirected to a third-party 

website or application, you are no longer governed by this Privacy Policy 

or our website’s Terms of Service.</p>

<h2>Changes to this privacy policy</h2>

<p>We reserve the right to modify this privacy policy and terms and 

conditions at any time. Changes and clarifications will take effect 

immediately upon their posting on the website.</p>

<p>We are under no obligation to notify you of any change so please review 

these terms frequently.</p>

<h2>Account and Users</h2>

<p>You must be 18 years to purchase from this website and at least the age 

of majority in your state or province of residence, you must provide us 

with your legal full name, a valid email address, store name and user 

password and any other information requested in order to complete the 

signup process.</p>

<p>You are responsible for maintaining the security of your account and 

password. We cannot and will not be liable for any loss or damage 

from your failure to comply with this security obligation, You agree 

to immediately notify us of any unauthorized use of customer or user 

passwords and accounts, or any breach of security.</p>

<p>Any and all personal information obtained from you is subject to our 

privacy policy (see Privacy Policy) and by agreeing to the Terms and 

Conditions your are also agreeing to the terms and conditions of such 

<h2>Privacy Policy</h2>

<p>Accounts registered by any type of automated method are not 

permitted.</p>

<p>Violation of any of the terms below will result in the termination of 

your Account When you subscribe to our services you agree to accept 

this policy. You retain the right to access, amend, correct or delete 

your personal information where it is inaccurate at any time. To do so, 

please contact info@foldway.com Cookies Our website uses "cookie" 

technology. Cookies enable us to customize our website to provide you 

with a better online service.</p>

<p>•  A cookie is a small amount of data, which often includes an 

anonymous unique identifie, that is sent to your browser from a web 

site's computers and stored on your computer's hard drive.</p>

<p>• Cookies are required to use our site.</p>

<p>•We use cookies to record current session information, but generally 

do not require permanent cookies.</p>

<p>• We also use log file information is automatically reported by your 

browser each time you access a web page, including information about 

your web request, IP address, browser type, clicks, domain names, 

landing pages, pages viewed, and other such information.</p>

<p>• We are not responsible for the privacy practices or the use of cookies 

on websites that you may have initially gained from other external 

websites that you may linked through our website.</p>

<p>• You may set your browser to block cookies, although doing so 

will adversely affect your ability to perform certain transactions, inhibit 

specific functions, and hinder access to certain content on our website.</p>

<h2>Data Storage</h2>

<p> We use third party hosting and other partners to provide the 

necessary hardware, software, networking, storage, and related 

technology required to run our services.</p>

<h2>Links To Other Websites</h2>

<p> Please remember that when you use a link to go from our website to 

another website, our Privacy Policy is no longer in effect. We are not 

responsible for the practices on websites linked to our website, or the 

information or content on these sites.</p>

<p>  Your browsing and interaction on any other website, including 

those that have a link on our website, is subject to that website’s own 

rules and policies. Please read over those rules and policies before 

proceeding.</p>

<h2>Analytics</h2>

<p> We use third party platforms to make accurate analysis of your data 

while you are navigating our website and we might provide you with info 

of goods and services which we consider can be interested for you.

<h2>User comments, feedbacks and other submissions</h2>

<p> If, at our request, you send certain specific submissions (for example 

contest entries) or without a request from us you send creative ideas, 

suggestions, proposals, plans, or other materials, whether online, by 

email, by postal mail, or otherwise (collectively, 'comments'), you 

agree that we may, at any time, without restriction, edit, copy, publish, 

distribute, translate and otherwise use in any medium any comments 

that you forward to us. We are and shall be under no obligation (1) to 

maintain any comments in confidence; (2) to pay compensation for any 

comments; or (3) to respond to any comments.</p>

<p> We may, but have no obligation to, monitor, edit or remove content that 

we determine in our sole discretion are unlawful, offensive, threatening, 

libelous, defamatory, pornographic, obscene or otherwise objectionable 

or violates any party’s intellectual property or these Terms of Service.</p>

<p> You agree that your comments will not violate any right of any third-
party, including copyright, trademark, privacy, personality or other 

personal or proprietary right. You further agree that your comments 

will not contain libelous or otherwise unlawful, abusive or obscene 

material, or contain any computer virus or other malware that could in 

any way affect the operation of the Service or any related website. You 

may not use a false e-mail address, pretend to be someone other than 

yourself, or otherwise mislead us or third-parties as to the origin of any 

comments. You are solely responsible for any comments you make and 

their accuracy. We take no responsibility and assume no liability for any 

comments posted by you or any third-party.</p>

<h2>Disclosure</h2>

<p> We may disclose your personal information if we are required by law to 

do so or if you violate our Terms of Service.</p>

<h2>Contact information</h2>

<p> If you would like to: access, correct, amend or delete any personal 

information we have about you, register a complaint, or simply want 

more information contact us at info@foldway.com</p>

<h2>Updates</h2>

<p> Updating your information is one of our highest priorities so as to 

improve our service accordingly. Please let us know if you have change 

email or any other info sending an email to info@foldway.com

Opt out If, after you opt-in, you change your mind, you would like to be 

removed from our mailing list and database for any reason ,you want 

to withdraw your consent for us to contact you, please contact us at 

info@foldway.com at any time.</p>

<h2>Questions?</h2>

<p> Any questions about this Privacy Policy should be addressed to 

info@foldway.com</p>





    </div>

   






    <?php echo $this->getChildHtml('footer') ?>



