<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>


<html>


<head>
<?php echo $this->getChildHtml('head') ?>

<style>
.idealtitle{
text-align: center;
}
.idealtitle h1{

font-family: Lato,sans-serif!important;
font-weight: 800;
font-size: 2.5em;
font-style: italic;

}

.dropmodelos{
  width: auto;
  height: auto;
  border: 3px solid #222222;
  padding: 2.5%;
  font-family: Lato,sans-serif!important;
  font-weight: 700;
  font-size: 1em;
  text-transform: uppercase;


}

.circlecrop{
    -webkit-clip-path: circle(38% at 50% 50%);
    clip-path: circle(38% at 50% 50%);




}
.overtext{
                  position: absolute;
                  top: 42%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                font-family: Lato,sans-serif;
                 font-weight: bold;
                  font-size:1.8em; 
                  text-transform:uppercase;
                  color:#111;
                  font-style:italic;
                  z-index:99999;
                   margin: 10%;
                   background-color: rgba(255,255,255,0.8);
                   width: 100% ;
                   height: auto;
                
}
.imgnav{
      width: 100%;
    padding: 0%;
    margin: 10%;
}


</style>



</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('header') ?>

    <div  style="text-align:center;" class="container">

          <div class="row">
             <a href="<?php  echo Mage::getBaseUrl(); ?>custom" class="homelink">
             <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Custom</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/custom.jpg'); ?>"  alt="">
            
               </div>   
             </div>
            </a>
            <a href="<?php  echo Mage::getBaseUrl(); ?>plegables" class="homelink">  
            <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Plegables</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/plegables.jpg'); ?>"  alt="">
            
           </div>  
           </div>   
            </a> 
           </div>  
           <div class="row">
            <a href="<?php  echo Mage::getBaseUrl(); ?>cascos" class="homelink"> 
            <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Cascos</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/cascos.jpg'); ?>"  alt="">
            
           </div>  
           </div> 
           </a>
           <a href="<?php  echo Mage::getBaseUrl(); ?>equipaje" class="homelink"> 
           <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Bolsos</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/equipaje.jpg'); ?>"  alt="">
            
           </div>  
           </div>    

          </a>
           </div>
            <div class="row">
              <a href="<?php  echo Mage::getBaseUrl(); ?>racks" class="homelink"> 
                <div class="col-xs-6 col-md-6">
                  <div class="circlecrop">
                <h2 class="overtext">Racks</h2>
                <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/racks.png'); ?>"  alt="">
                
               </div>  
               </div>   
           </a>  
             <a href="<?php  echo Mage::getBaseUrl(); ?>ninos" class="homelink"> 
                <div class="col-xs-6 col-md-6">
                   <div class="circlecrop">
                <h2 class="overtext">Niños</h2>
                <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/ninos.png'); ?>"  alt="">
                
               </div>  
               </div>   
             </a>
      
           </div>   
            <div class="row">
              <a href="<?php  echo Mage::getBaseUrl(); ?>luces" class="homelink"> 
            <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Luces</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/luces.jpg'); ?>"  alt="">
            
           </div>  
           </div>   
             </a>
             <a href="<?php  echo Mage::getBaseUrl(); ?>infladores" class="homelink"> 
            <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Infladores</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/infladores.jpg'); ?>"  alt="">
            
           </div>  
           </div>
           </a>  
           </div>     
            <div class="row">
              <a href="<?php  echo Mage::getBaseUrl(); ?>candados" class="homelink"> 
            <div class="col-xs-6 col-md-6">
               <div class="circlecrop">
            <h2 class="overtext">Candados</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/candados.jpg'); ?>"  alt="">
            
           </div>  
           </div>   
         </a>
         <a href="<?php  echo Mage::getBaseUrl(); ?>otros" class="homelink"> 
            <div class="col-xs-6 col-md-6">
              <div class="circlecrop">
            <h2 class="overtext">Otros</h2>
            <img  class="imgnav" src="<?php echo $this->getSkinUrl('images/mobilenav/otros.jpg'); ?>"  alt="">
            
           </div>  
           </div>   
        </a>
           </div>
                    

      </div>  















    </div>  



    <?php echo $this->getChildHtml('footer') ?>


