<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>


<html>


<head>
<?php echo $this->getChildHtml('head') ?>

</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('header') ?>




    <div class="shippings">
        <h1>Términos y condiciones</h1>














        <h2>Aceptación y conocimiento de los términos y condiciones</h2>

        <p>
            Lea los términos y condiciones generales (en adelante, los "Términos y condiciones") que se describen a continuación. Estos se aplicaran para la navegacion del sitio de internet www.lordbike.com.ar (en adelante, el "sitio" cuando se refiera al sitio web de internet) y los servicios ofrecidos en el.
            El sitio www.lordbike.com.ar, es propiedad de Enrique Gustavo Almada (en adelante, "Lord Bike").
            Los presentes términos y condiciones tienen carácter obligatorio y vinculante. se aplican a todas las compras y actividades realizadas mediante el sitio. El uso del sitio implica el conocimiento y la aceptación de ellos. Si usted no está de acuerdo con los términos y condiciones, deberá abstenerse de utilizar el sitio y/o los servicios por él ofrecidos.


        </p>  



        <h2>Modificación de los términos y condiciones</h2>

        <p>    
            Los términos y condiciones podrán ser sustituidos o sufrir modificaciones en cualquier momento y a exclusivo criterio de Lord Bike y no se requerirá a los usuarios su consentimiento. Para las transacciones en curso que hayan comenzado con anterioridad a dichas modificaciones, subsistirán las condiciones vigentes al momento de su concertación, a menos que las nuevas modificaciones introducidas fueran más convenientes para el usuario.
 
            Lord Bike deberá poner un aviso en el sitio alertando a los usuarios sobre estos cambios, durante un tiempo razonable. Sin perjuicio de lo anterior, los usuarios son responsables de leer estos términos y condiciones cada vez que ingresen al sitio para ver si han sufrido modificaciones.
  
        </p>       



        <h2>Interrupción del servicio – exclusión de responsabilidad.</h2>

        <p>    
            Lord Bike se reserva el derecho de interrumpir, suspender o modificar en cualquier momento los servicios ofrecidos en el presente sitio, ya sea en forma permanente o transitoria. No se requerirá la conformidad de los usuarios, ni será necesario aviso previo alguno.
 
            Asimismo, Lord Bike no garantiza el acceso o uso permanente del sitio, ya que éste podría interrumpirse por cuestiones técnicas ajenas a Lord Bike.
            No obstante lo mencionado anteriormente, si la suspensión o interrupción mencionada no obedeciere a razones de fuerza mayor o caso fortuito, Lord Bike se compromete a cumplir las prestaciones que estuvieran pendientes al momento de la suspensión o interrupción.
  
        </p>       

        <h2>Veracidad de la información suministrada.</h2>

        <p>    
            Para poder utilizar el sitio de manera eficiente y segura, los usuarios deberán aportar ciertos datos, entre ellos, su nombre y apellido, domicilio,  cuenta de e-mail, documento de identidad, sin los cuales se tornaría imposible brindar los servicios. Por eso se requiere que éstos sean verdaderos y exactos.
            Cuando se ingresan datos y números correspondientes a tarjetas de crédito, estos son encriptados, asegurando así que se mantengan en total confidencialidad y no puedan ser vistos por otras personas.
 
            En caso de que la información o los datos suministrados por el usuario no sea verdadera, éste será responsable por los daños que este hecho pudiera ocasionar.
 
  
        </p>       

        <h2>     Seguridad de sus datos</h2>
        <p>
            Para mantener los datos de su compra seguros, son encriptados mediante el servicio SSL de COMODO GROUP INC. Toda su informacion es procesada luego por el servicio "MERCADOPAGO" de MercadoLibre S.R.L. No nos hacemos cargo por la interrupcion o mal funcionamiento de sus servicios.
        </p>

         <h2>  Fotos</h2>
        <p>
Hemos hecho un gran esfuerzo para representar lo mas precisamente posible los colores e imagenes de los productos que aparecen en nuestro sitio. No podemos asegurar que la pantalla de su computadora o dipositivo movil pueda representarlos de manera correcta.
        </p>
         <h2> Informacion y precios</h2>
        <p>

Hacemos todo esfuerzo posible para mantener precios actuales y precisos en nuestro catalogo online. Y apuntamos a la misma presicion con toda la informacion presentada en nuestro sitio. Apreciamos su entendimiento si por cualquier motivo alguno de los precios o informacion presentada es incorrecta. 
        </p>



     <h2>Devoluciónes</h2>
       <p>
Los usuarios que compren a través de este sitio tienen cinco (5) días a partir de la recepción del producto para realizar la devolución del mismo.
El producto en cuestión deberá ser devuelto en las mismas condiciones que se envió, no deberán estar usados y tendrán que contar con el embalaje correspondiente.
Una vez que el producto sea recibido y verificado el correcto estado del mismo, se procederá al reintegro.
El dinero se reintegrará al comprador vía tránsferencia bancaria a la cuenta del titular de la compra, si este no posee cuenta, deberá dejar expresa constancia de la cuenta en donde quiere que se le deposite el dinero. Los gastos de envío de la devolución del producto correrán por cuenta del comprador.
     </p>

    <h2>Garantía</h2>

<p>
Todos los productos vendidos a través de este sitio  cuentan con la garantía del proovedor o fabricante del mismo, las mismas pueden variar en su extensión siendo Lord Bike un nexo entre el comprador y el fabricante o proovedor, los tiempos de reparación de los productos pueden variar según el fabricante o proovedor.
</p>

<h2>
Medios de pago
</h2>


<p>
Los medios de pago disponibles en el sitio son ofrecidos por el servicio "Mercadopago", de Mercado Libre SRL. Las promociones existentes pueden variar sin aviso previo. Mercado Libre SRL es responsable de las operaciones de cobro y el banco emisor de la tarjeta de crédito del comprador de brindar el crédito correspondiente a la compra.


</p>
<h2>
Promociones
</h2>


<p>
Las promociones anunciadas en este sitio no son acumulables, solo son válidas por separado.


</p>
<h2>
Envíos 
</h2>
<p>
Todos los envíos exceptuando los de bicicletas son realizadas a través OCA, en todo el territorio de la República Argentina exceptuando Tierra del Fuego.
Las compras por montos superiores a $2000 serán sin cargo para el comprador, por importes menores a $2000 el comprador deberá informarse del costo de dicho envio, previo a la compra de el/los producto/s. Los envios sin cargo no son acumulables a otras promociones y/o beneficios ofrecidos en este sitio.
El transporte para el envío de bicicletas compradas en este sitio será elegido por Lord Bike, de a cuerdo a la opcion más conveniente en relacion a la úbicacion geografica del cliente.

La mercadería viaja por cuenta y orden del comprador.Una vez enviado el/los productos, Lord Bike no se hará cargo por el extravío o rotura del mismo. Siendo la empresa transportista la responsable en esos casos.
Lord Bike se reserva el derecho de no realizar envios en determinadas situaciones
</p>







          <h2>Cookies</h2>
        <p>

 
El sitio puede utilizar un sistema de seguimiento mediante “cookies”, para que el acceso a la información, al pasar de página en página, se realice con mayor rapidez. También ayuda en algunos casos a identificar a los usuarios, sin necesidad de solicitarles la clave de acceso una y otra vez.
 
Estas cookies son pequeños archivos que envía la página visitada y se alojan en el disco duro del ordenador, ocupando poco espacio.
 
Se hace saber a los usuarios que utilizando las opciones de su navegador podrán limitar o restringir según su voluntad el alojamiento de estas “cookies”, aunque es desaconsejable restringirlas totalmente.

 

        </p>
        <h2>Validez de las promociones</h2>
        <p>

 

        En el caso de que se realicen ofertas y promociones de productos, éstas tendrán validez para las compras efectuadas desde la fecha de comienzo de las mismas, hasta la de finalización de la oferta. Los términos y condiciones de las mismas serán comunicados en el sitio, y estarán siempre sujetas a la existencia en stock de los productos ofrecidos.

 

        </p>
         <h2>Impuesto al valor agregado (IVA)</h2>
        <p>

 

        Todos los precios expresados en el sitio incluyen iva, salvo que se indique lo contrario.
 

        </p>
          <h2>Jurisdicción y ley aplicable</h2>
        <p>

 

        Los presentes términos y condiciones se encuentran regidos sin excepción y en todos sus puntos por las leyes de la república argentina y serán interpretados de acuerdo a ellas.
 
        Ante cualquier diferencia, desacuerdo o conflicto derivado de la interpretación, validez, alcance y/o aplicación de los presentes términos y condiciones generales, los usuarios se comunicarán conde manera fehaciente, haciéndole llegar su reclamo, para que las partes traten de arribar a un acuerdo.
         
        En caso de que no sea posible arribar a una solución, y para garantizar a los consumidores el pleno acceso a la justicia, los usuarios podrán elegir y someter su reclamo a una de las siguientes opciones e instancias:

     </p>
        <p>
         
        a)      Sistema nacional de arbitraje de consumo del ministerio de economía y producción de la nación. Los procedimientos ante este sistema son gratuitos, y no es necesario contar con patrocinio letrado. asimismo, se garantiza el equilibrio entre las partes y la transparencia del proceso, y los laudos emitidos por dicho tribunal tienen autoridad de cosa juzgada y son irrecurribles (para saber más sobre este sistema ingresar en http://www.mecon.gov.ar/snac)
         

          </p> 
             <p>
        b)      Dirección general de defensa y protección del consumidor del gobierno de la ciudad de buenos aires (para saber más sobre este sistema ingresar en http://www.buenosaires.gov.ar)


          </p>
             <p>
         
        c)      Tribunales ordinarios de la capital federal con competencia en la materia.


          </p>
             <p>
        Una vez elegida una de las opciones, se excluyen las demás alternativas.
         
        Para el caso de que cualquiera de las opciones anteriores fuesen gravosas o económicamente inviables para usuarios domiciliados en el exterior, las partes, a pedido del usuario, determinarán de común acuerdo un mecanismo mutuamente conveniente para resolver sus diferencias.


 

        </p>
    
    

    

    







         </div>

    </div>









































    <?php echo $this->getChildHtml('footer') ?>


