  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/1gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>1 speed</h2>
  	  	<p>
  	  		The purist's choice: light, simple and without clutter.



  	  	</p>

  
  	 </div>



</div>