  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/2gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>2 speeds</h2>
  	  	<p>
  	  		Based on the unique Brompton derailleur system, with near perfect chain-alignment, this is the best set-up for flexibility and portabilty: one gear for hills and starting off, one for cruising.


  	  	</p>

  
  	 </div>



</div>