  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/3gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>3 speeds</h2>
  	  	<p>
  	  		The BSR (Brompton Standard Range) hub is an updated version o f the classic Sturney Archer three-speed hub in an aluminium alloy shell. Fully enclosed for reiability and easy to use: a popular choice for everyday cycling.



  	  	</p>

  
  	 </div>



</div>