  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/6gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>6 speeds</h2>
  	  	<p>
  	  		Combining the highly-efficient BWR (Brompton wide range) hub with a derailleur system gives six evenly-spaced gears. Whith low transmission losses and wide range, this is the right choice for touring and for hilly areas.



  	  	</p>

  
  	 </div>



</div>