  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/3gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>3 speeds</h2>
  	  	<p>
  	  		The LED rear lamp with integral reflectors, whitch stays fixed to the bike, was designed especially for Brompton and gives a good bright light. At the front is the neat, powerful 3-LED battery lamp, easily removed for folding with a quick-release.



  	  	</p>

  
  	 </div>



</div>