  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/bromptonkevlar.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Brompton Kevlar</h2>
  	  	<p>
  	  		Brompton's standard tyre; durable yet light and with low rolling resistance. The kevlar belt under the tread almost eliminates puncutres. Finished with reflective sidewalls.



  	  	</p>

  
  	 </div>



</div>