  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/bromptonsaddle.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Brompton saddle</h2>
  	  	<p>
  	  		Comfortable, practical and light: this high-quality unisex saddle has been designed by Brompton for their bikes. A moulded grip under the nose facilitates carrying, and the ingenious Brompton Pentaclip alllows stepless adjusment of the saddle angle.



  	  	</p>

  
  	 </div>



</div>