  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/3gear.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>3 speeds</h2>
  	  	<p>
  	  		S MODEL RE PIOLAA S;DOIGASDL;GIHSD
  	  		DFHSDF
  	  		HFAHADFH
  	  		ADFH



  	  	</p>

  
  	 </div>



</div>