  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/firm.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Firm suspension</h2>
  	  	<p>
  	  		Possibly more suitable for those weighing over 80kg, those who cycle more aggressively and those prepared to sacrifice some comfort in return for a more responsive ride.



  	  	</p>

  
  	 </div>



</div>