  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/h.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>H Type</h2>
  	  	<p>
  	  		Combining the classic looks of the M type with a markedly more upright riding position (height 1072mm), albeit at the cost of a additional weight, the H Type is for those who loke to travel with unhurried style.


  	  	</p>

  
  	 </div>



</div>