  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/kojak.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Schwable Koyak</h2>
  	  	<p>
  	  		The fastest tyre ever fitted on the Brompton; light and puncture resistant (thanks to a RaceGuard strip)
, a Kevlar bead also allows it to be folded, making it easy to pack as a spare. Finished with reflective sidewalls.


  	  	</p>

  
  	 </div>



</div>