  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/marathon.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Shwable Marathon</h2>
  	  	<p>
  	  		Heavier than the Brompton Tyre and noticeably slower, but it is solidly-built, with Schwable green guard puncture protection and a thicker sidewall to make the tyre more robust. Finished with reflective sidewalls.


  	  	</p>

  
  	 </div>



</div>