  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/m.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>M Type</h2>
  	  	<p>
  	  		The original Brompton 'look' offering a more upright ride (height 1015mm), at the cost of a little more weight. The all-rounder in the range, with plenty of room for luggage at the front.



  	  	</p>

  
  	 </div>



</div>