  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/p.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>P Type</h2>
  	  	<p>
  	  		Designet with the touring cyclist in mind, two positions (height 1033mm and 880mm) offer the rider a choice between an aerodynamic profile and more upright control, ideal in traffic. The pay-off is a noticeably heavier front end.



  	  	</p>

  
  	 </div>



</div>