  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/r.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Mudguards & Rack</h2>
  	  	<p>
  	  		A carrier on the bike can be useful and it does increase the stability of the folded package. The die-cast aluminuim rack ocmes with shock cords and can easily manage loads of up to 10kg.



  	  	</p>

  
  	 </div>



</div>