  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/shimano_dynamo.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Shimano dynamo</h2>
  	  	<p>
  	  		Hub dynamos offer a very reiable lighting solution and this one, especially adapted for the Brompton by shimano, offers very good performance at a keen price. Features include  Busch & Muller "Lyt B" LED front lamp and a stand light function at the rear.



  	  	</p>

  
  	 </div>



</div>