  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/s.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>S type</h2>
  	  	<p>
  	  		Straight, low bars (grip height 935mm) offering a sporty ride position and a lightweight, positive feel. The pay off is less room for front luggage.



  	  	</p>

  
  	 </div>



</div>