  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/son_dynamo.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Son dynamo</h2>
  	  	<p>
  	  		The SON hub is beautifully engineered, highly efficient, and will give years of reliable service. A powerful Busch & Muller, LED front lamp, featuing an automatic light-sensing function, and a stand-light funciton at the front as well as the rear, complete the premium package.



  	  	</p>

  
  	 </div>



</div>