  <style>
  .featurestexto{
  	text-align: left;
  }


  </style>


  <div class="section group">
  	 <div class="col span_3_of_8 featuresimg">

       <img class="img-responsive" alt="Responsive image" src="<?php echo $this->getSkinUrl('images/bromptonparts/standard.png'); ?>" />
  	 </div>
  	  <div class="col span_5_of_8 featurestexto">
  	  	<h2>Standard Suspension</h2>
  	  	<p>
  	  		Fine for many, particulary lighter people and those who ride and pedal smoothly.



  	  	</p>

  
  	 </div>



</div>